### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by buaa1989** [hellloxiaotian/LESRCNN#3]
我单个GPU（GTX 1660 Ti显卡）训练 x2 model，batchsize改为1， 仍然显示 RuntimeError: CUDA error: out of memory。这个正常吗
谢谢。

**Comment by buaa1989** [comment]
我训练x3 model，batchsize改为1 显示 RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR。谢谢

**Comment by buaa1989** [comment]
已解决

**Comment by aatiqa-ghazali** [comment]
@buaa1989  
From Which file did you change the batch size?

**Comment by aatiqa-ghazali** [comment]
@buaa1989 How did you solve the error?And how much time it took for training

**Comment by aatiqa-ghazali** [comment]
@buaa1989 你是如何解决错误的？ 训练花了多少时间
